import type { Metadata } from "next";
import localFont from "next/font/local";
import "@styles/globals.css";
import {DataProvider} from "@context/DataContext";
import { Suspense, ReactNode } from "react";
import Loader from "@components/Loader";
import {CsvProvider} from "@context/CsvContext";

const geistSans = localFont({
  src: "../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode; }>) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased2`}
      >
        <h1>Business Processes Simulator</h1>

        <DataProvider>
          <CsvProvider>
            <div className='max-w-screen-lg mx-auto p-4'>
              <Suspense fallback={<Loader />}>{children}</Suspense>
            </div>
          </CsvProvider>
        </DataProvider>
      </body>
    </html>
  );
}

export default RootLayout;
