import type { Metadata } from "next";
import "@assets/styles/globals.css";
import {DataProvider} from "@context/DataContext";
import {Suspense, ReactNode} from "react";
import Loader from "@components/Loader";
import {CsvProvider} from "@context/CsvContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode; }>) => {
  return (
    <html lang="en">
      <body className={'antialiased2'}>
        <h1>Business Processes Simulator</h1>

        <DataProvider>
          <CsvProvider>
            <Suspense fallback={<Loader />}>{children}</Suspense>
          </CsvProvider>
        </DataProvider>
      </body>
    </html>
  );
}

export default RootLayout;
